# -*- coding: utf-8 -*-
"""prescription-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WK4S7kYlx7Om1IH521iNC_q8kwTZ45RO
"""

pip install request
sudo apt install tesseract-ocr
pip install pytesseract pillow
pip install openai
import pytesseract
from PIL import Image
import requests
from io import BytesIO
import openai
import random

api_key = "sk-proj-bhI8ZDrOTZiaGcpT5j8gT3BlbkFJux0Z3t4SItZYfsq7i1nX"
def ask_chatgpt(query):
    url = "https://api.openai.com/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    data = {
        "model": "gpt-3.5-turbo",
        "messages": [{"role": "user", "content": query}]
    }

    response = requests.post(url, json=data, headers=headers)
    response.raise_for_status()  # Raises an exception for HTTP errors
    response_data = response.json()

    # Extracting the answer text from the response
    answer = response_data.get('choices')[0].get('message').get('content')
    return answer

# Load and process the image
def load_image(image_path):
    image = Image.open(image_path)
    display(image)
    return image

# Apply OCR to the image
def extract_text(image):
    text = pytesseract.image_to_string(image)
    return text

# Putting it all together
def main(image_path):
    image = load_image(image_path)
    extracted_text = extract_text(image)
    print("Extracted Text:", extracted_text)
    prompt = f" Assume you're a health care professional and you've been trained on vast amounts of medical data. Looking at this prescription, provide more information about this prescription. {extracted_text}"
    info = ask_chatgpt(prompt)
    print("Generated Information:", info)

# User Input in colab
from google.colab import files
uploaded = files.upload()
for filename in uploaded.keys():
    main(filename)