# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozIcKhF_UbytCHcohWXRDFNu3C7b_tA7
"""

!pip install requests

"""CHATBOT PART -- QUESTION ANSWERING"""

import requests

api_key = "sk-proj-bhI8ZDrOTZiaGcpT5j8gT3BlbkFJux0Z3t4SItZYfsq7i1nX"
def ask_chatgpt(query):
    url = "https://api.openai.com/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }
    data = {
        "model": "gpt-3.5-turbo",
        "messages": [{"role": "user", "content": query}]
    }

    response = requests.post(url, json=data, headers=headers)
    response_data = response.json()

    # Extracting the answer text from the response
    answer = response_data.get('choices')[0].get('message').get('content')
    return answer

question = input("Enter your query: ")
prompt = f"Answer what I am asking related to livestock, disease. Also prescribe me names of medicines which I can give my livestock if possible.{question}"
response_data = ask_chatgpt(prompt)
print(response_data)

"""IMAGE RECOGNITION"""

# Install pytesseract and Pillow for image processing
!sudo apt install tesseract-ocr
!pip install pytesseract pillow
!pip install openai

# Import Libraries
import pytesseract
from PIL import Image
import requests
from io import BytesIO
import openai

# Load and process the image
def load_image(image_path):
    image = Image.open(image_path)
    display(image)
    return image

# Apply OCR to the image
def extract_text(image):
    text = pytesseract.image_to_string(image)
    return text

# Putting it all together
def main(image_path):
    image = load_image(image_path)
    extracted_text = extract_text(image)
    print("Extracted Text:", extracted_text)
    prompt = f" Assume you're a health care professional and you've been trained on vast amounts of medical data. Looking at this prescription, provide more information about this prescription. {extracted_text}"
    info = ask_chatgpt(prompt)
    print("Generated Information:", info)

# Example Usage
# main('path_to_image.jpg')

# User Input in colab
from google.colab import files
uploaded = files.upload()
for filename in uploaded.keys():
    main(filename)

"""STORE CHAT HISTORY IN DATABASE"""

# !pip install pymongo dnspython
# !pip install "pymongo[srv]"

# from pymongo.mongo_client import MongoClient
# from pymongo.server_api import ServerApi

# # Make sure to replace `<password>` with your actual password, properly URL-encoded if necessary
# # uri = "mongodb+srv://ashfaqaqsa883:<RQavPYfFiqkAmlkL>@cluster0.whmef7a.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
# uri = "mongodb+srv://ashfaqaqsa883:<RQavPYfFiqkAmlkL>@cluster0.whmef7a.mongodb.net/"

# # Create a new client and connect to the server
# client = MongoClient(uri, server_api=ServerApi('1'))

# # Send a ping to confirm a successful connection
# try:
#     client.admin.command('ping')
#     print("Pinged your deployment. You successfully connected to MongoDB!")
# except Exception as e:
#     print(e)

